/**
 * Finish library for Boise Cabinet Co door and box surfaces.
 */

import type { FinishCategory } from "./doorStyles";

export type FinishTier = "standard" | "premium" | "reserve";
export type FinishSheen = "flat" | "matte" | "satin" | "semi-gloss" | "gloss" | "high-gloss";

export interface Finish {
  id: string;
  name: string;
  slug: string;
  category: FinishCategory;
  sheen: FinishSheen;
  hexColor: string;
  tier: FinishTier;
  compatibleDoorStyleIds: string[];
  description?: string;
  /** One Source / Tafisa panel product name when verified */
  supplierColorName?: string;
  supplierPanelBrand?: "Tafisa" | "Salt International";
  /** Optimized swatch texture path */
  imagePath?: string;
}

export const FINISHES: Finish[] = [
  // ── Matte (15) ──────────────────────────────────────────────────────────
  {
    id: "matte-snowcap",
    name: "Snowcap",
    slug: "snowcap",
    category: "matte",
    sheen: "matte",
    hexColor: "#F5F3EF",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Warm white with a hint of cream, brightens north-facing Boise kitchens without stark glare.",
  },
  {
    id: "matte-glacier",
    name: "Glacier",
    slug: "glacier",
    category: "matte",
    sheen: "matte",
    hexColor: "#E8EBED",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Cool neutral white suited to contemporary slab and thin-shaker profiles.",
  },
  {
    id: "matte-dune",
    name: "Dune",
    slug: "dune",
    category: "matte",
    sheen: "matte",
    hexColor: "#D4C9B8",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "three-piece", "beta-shaker"],
    description: "Sandy beige that complements Idaho sandstone and warm quartz countertops.",
  },
  {
    id: "matte-sagebrush",
    name: "Sagebrush",
    slug: "sagebrush",
    category: "matte",
    sheen: "matte",
    hexColor: "#8B9A7E",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Muted green-gray inspired by high-desert foothills near Eagle and Hidden Springs.",
  },
  {
    id: "matte-slate",
    name: "Slate",
    slug: "slate",
    category: "matte",
    sheen: "matte",
    hexColor: "#5C6369",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Charcoal gray for lower cabinets or full monochrome kitchen schemes.",
  },
  {
    id: "matte-midnight",
    name: "Midnight",
    slug: "midnight",
    category: "matte",
    sheen: "matte",
    hexColor: "#2C3338",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "beta-shaker"],
    description: "Deep navy-black matte for dramatic island bases and entertainment built-ins.",
  },
  {
    id: "matte-clay",
    name: "Clay",
    slug: "clay",
    category: "matte",
    sheen: "matte",
    hexColor: "#B8957A",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "three-piece"],
    description: "Terracotta-leaning neutral that pairs with brass hardware and natural stone.",
  },
  {
    id: "matte-fog",
    name: "Fog",
    slug: "fog",
    category: "matte",
    sheen: "matte",
    hexColor: "#C5C8C4",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Soft gray-green for laundry rooms and mudrooms where fingerprints show less.",
  },
  {
    id: "matte-linen",
    name: "Linen",
    slug: "linen",
    category: "matte",
    sheen: "matte",
    hexColor: "#E5DDD0",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "three-piece", "alpha-shaker", "beta-shaker"],
    description: "Textured-look matte in warm off-white, a Reserve favorite for whole-home packages.",
  },
  {
    id: "matte-riverstone",
    name: "Riverstone",
    slug: "riverstone",
    category: "matte",
    sheen: "matte",
    hexColor: "#9A9590",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Medium warm gray with subtle depth for transitional kitchens in Meridian subdivisions.",
  },
  {
    id: "matte-basalt",
    name: "Basalt",
    slug: "basalt",
    category: "matte",
    sheen: "matte",
    hexColor: "#3D4044",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "beta-shaker"],
    description: "Near-black with brown undertones, references Idaho basalt columns without gloss reflection.",
  },
  {
    id: "matte-mist",
    name: "Mist",
    slug: "mist",
    category: "matte",
    sheen: "flat",
    hexColor: "#D8DCE0",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Ultra-flat pale gray for handleless slab kitchens and minimalist baths.",
  },
  {
    id: "matte-terracotta",
    name: "Terracotta",
    slug: "terracotta",
    category: "matte",
    sheen: "matte",
    hexColor: "#A86B52",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "beta-shaker"],
    description: "Earthy rust tone for accent islands and butler's pantry statements.",
  },
  {
    id: "matte-fern",
    name: "Fern",
    slug: "fern",
    category: "matte",
    sheen: "matte",
    hexColor: "#4A6B52",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Deep forest green for mudrooms, home bars, and library built-ins.",
  },
  {
    id: "matte-pebble",
    name: "Pebble",
    slug: "pebble",
    category: "matte",
    sheen: "matte",
    hexColor: "#AEA89E",
    tier: "reserve",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "alpha-shaker", "beta-shaker"],
    description: "Reserve-exclusive greige with a hand-applied texture effect.",
  },

  // ── Gloss (12) ──────────────────────────────────────────────────────────
  {
    id: "gloss-porcelain",
    name: "Porcelain",
    slug: "porcelain",
    category: "gloss",
    sheen: "high-gloss",
    hexColor: "#FAFAF8",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Mirror-bright white for contemporary kitchens with waterfall islands.",
  },
  {
    id: "gloss-ivory",
    name: "Ivory",
    slug: "ivory",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#F0EBE0",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Soft gloss cream, easier to maintain than high-gloss in busy family kitchens.",
  },
  {
    id: "gloss-pearl",
    name: "Pearl",
    slug: "pearl",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#E2E4E8",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Light gray gloss with a subtle pearlescent shift in direct sun.",
  },
  {
    id: "gloss-graphite",
    name: "Graphite",
    slug: "graphite",
    category: "gloss",
    sheen: "high-gloss",
    hexColor: "#4A4E54",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker"],
    description: "Reflective charcoal for sleek slab uppers paired with matte bases.",
  },
  {
    id: "gloss-obsidian",
    name: "Obsidian",
    slug: "obsidian",
    category: "gloss",
    sheen: "high-gloss",
    hexColor: "#1A1D20",
    tier: "premium",
    compatibleDoorStyleIds: ["slab"],
    description: "Deep black gloss reserved for slab-only applications and appliance panels.",
  },
  {
    id: "gloss-seafoam",
    name: "Seafoam",
    slug: "seafoam",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#A8C4BC",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Coastal-inspired aqua gloss popular in Boise Bench bungalow refreshes.",
  },
  {
    id: "gloss-blush",
    name: "Blush",
    slug: "blush",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#D4A89A",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Dusty rose gloss for vanity suites and dressing-room built-ins.",
  },
  {
    id: "gloss-cobalt",
    name: "Cobalt",
    slug: "cobalt",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#3D5A80",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker"],
    description: "Bold blue gloss for island accents and wet-bar focal points.",
  },
  {
    id: "gloss-champagne",
    name: "Champagne",
    slug: "champagne",
    category: "gloss",
    sheen: "semi-gloss",
    hexColor: "#D9CEB8",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Warm metallic-leaning semi-gloss that complements brushed gold hardware.",
  },
  {
    id: "gloss-storm",
    name: "Storm",
    slug: "storm",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#6B7280",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Medium gray gloss with even reflectivity for two-tone kitchen designs.",
  },
  {
    id: "gloss-alabaster",
    name: "Alabaster",
    slug: "alabaster",
    category: "gloss",
    sheen: "semi-gloss",
    hexColor: "#EDE8DF",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker"],
    description: "Low-luster gloss alternative for clients who want sheen without mirror finish.",
  },
  {
    id: "gloss-crimson",
    name: "Crimson",
    slug: "crimson",
    category: "gloss",
    sheen: "gloss",
    hexColor: "#8B3A3A",
    tier: "reserve",
    compatibleDoorStyleIds: ["slab", "modern-shaker"],
    description: "Reserve-exclusive deep red gloss for statement pantries and wine rooms.",
  },

  // ── Woodgrain (15) ──────────────────────────────────────────────────────
  {
    id: "wood-white-oak",
    name: "White Oak",
    slug: "white-oak",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#C4A882",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "three-piece", "alpha-shaker", "beta-shaker"],
    description: "Natural white oak grain with clear satin topcoat, our most versatile wood finish.",
  },
  {
    id: "wood-natural-walnut",
    name: "Natural Walnut",
    slug: "natural-walnut",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#6B5344",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "three-piece", "alpha-shaker", "beta-shaker"],
    description: "Rich brown walnut with visible grain movement for primary kitchens and offices.",
  },
  {
    id: "wood-espresso-walnut",
    name: "Espresso Walnut",
    slug: "espresso-walnut",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#3E2E24",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "three-piece", "alpha-shaker", "beta-shaker"],
    description: "Dark-stained walnut for traditional three-piece and alpha-shaker libraries.",
  },
  {
    id: "wood-honey-maple",
    name: "Honey Maple",
    slug: "honey-maple",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#D4A855",
    tier: "standard",
    compatibleDoorStyleIds: ["modern-shaker", "thin-shaker", "three-piece"],
    description: "Warm golden maple suited to Spec Grade kitchens and rental refreshes.",
  },
  {
    id: "wood-driftwood",
    name: "Driftwood",
    slug: "driftwood",
    category: "woodgrain",
    sheen: "matte",
    hexColor: "#A89F94",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Weathered gray oak tone for mountain-modern homes in the Boise Foothills.",
  },
  {
    id: "wood-charcoal-oak",
    name: "Charcoal Oak",
    slug: "charcoal-oak",
    category: "woodgrain",
    sheen: "matte",
    hexColor: "#4A4540",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "beta-shaker"],
    description: "Smoked oak with muted grain, pairs with black hardware and concrete counters.",
  },
  {
    id: "wood-hickory",
    name: "Hickory",
    slug: "hickory",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#B8956A",
    tier: "standard",
    compatibleDoorStyleIds: ["modern-shaker", "thin-shaker", "three-piece"],
    description: "Pronounced grain pattern for rustic-transitional kitchens in Kuna and Star.",
  },
  {
    id: "wood-cherry",
    name: "Cherry",
    slug: "cherry",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#8B5A42",
    tier: "premium",
    compatibleDoorStyleIds: ["three-piece", "alpha-shaker", "modern-shaker"],
    description: "Red-toned cherry for North End craftsman and traditional built-in libraries.",
  },
  {
    id: "wood-ash",
    name: "Ash",
    slug: "ash",
    category: "woodgrain",
    sheen: "matte",
    hexColor: "#B8AEA0",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Light ash with subtle cathedral grain for Scandinavian-inspired interiors.",
  },
  {
    id: "wood-teak",
    name: "Teak",
    slug: "teak",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#9A7B5A",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "alpha-shaker"],
    description: "Warm golden-brown teak tone for outdoor kitchen cabinetry and wet bars.",
  },
  {
    id: "wood-reclaimed-barn",
    name: "Reclaimed Barn",
    slug: "reclaimed-barn",
    category: "woodgrain",
    sheen: "matte",
    hexColor: "#7A6A58",
    tier: "reserve",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "beta-shaker"],
    description: "Reserve-exclusive wire-brushed texture mimicking aged barn wood.",
  },
  {
    id: "wood-ebony",
    name: "Ebony",
    slug: "ebony",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#2A2520",
    tier: "premium",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "alpha-shaker", "beta-shaker"],
    description: "Near-black wood stain with faint grain visibility for luxe primary suites.",
  },
  {
    id: "wood-blonde-oak",
    name: "Blonde Oak",
    slug: "blonde-oak",
    category: "woodgrain",
    sheen: "matte",
    hexColor: "#DCC9A8",
    tier: "standard",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "thin-shaker", "beta-shaker"],
    description: "Light bleached oak popular in open-concept Eagle and Meridian great rooms.",
  },
  {
    id: "wood-pecan",
    name: "Pecan",
    slug: "pecan",
    category: "woodgrain",
    sheen: "satin",
    hexColor: "#A08060",
    tier: "standard",
    compatibleDoorStyleIds: ["modern-shaker", "thin-shaker", "three-piece"],
    description: "Medium brown with varied grain for whole-home Spec Grade packages.",
  },
  {
    id: "wood-cedar",
    name: "Cedar",
    slug: "cedar",
    category: "woodgrain",
    sheen: "matte",
    hexColor: "#A87858",
    tier: "reserve",
    compatibleDoorStyleIds: ["slab", "modern-shaker", "beta-shaker"],
    description: "Reserve outdoor-rated cedar tone for covered patio and outdoor kitchen lines.",
  },
];

export const FINISH_BY_SLUG = Object.fromEntries(
  FINISHES.map((f) => [f.slug, f]),
) as Record<string, Finish>;

export const FINISH_BY_ID = Object.fromEntries(
  FINISHES.map((f) => [f.id, f]),
) as Record<string, Finish>;

export const FINISHES_BY_CATEGORY = FINISHES.reduce(
  (acc, finish) => {
    if (!acc[finish.category]) acc[finish.category] = [];
    acc[finish.category].push(finish);
    return acc;
  },
  {} as Record<FinishCategory, Finish[]>,
);
