#!/usr/bin/env node
/**
 * Generate shared/catalog/generated/*.ts from data/supplier-catalog/*.json
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const DATA = path.join(ROOT, "data/supplier-catalog");
const OUT = path.join(ROOT, "shared/catalog/generated");

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(DATA, name), "utf8"));
}

function bySlugConst(arrayName) {
  const map = {
    FINISHES: "FINISH",
    DOOR_STYLES: "DOOR_STYLE",
    COLLECTIONS: "COLLECTION",
    CABINET_PRODUCTS: "CABINET_PRODUCT",
  };
  const base = map[arrayName] ?? (arrayName.endsWith("S") ? arrayName.slice(0, -1) : arrayName);
  return `${base}_BY_SLUG`;
}

function emitConst(name, typeName, data, exportType = true) {
  const json = JSON.stringify(data, null, 2);
  const typeExport = exportType ? `export type { ${typeName} } from "../types";\n` : "";
  const bySlug = bySlugConst(name);
  return `/** AUTO-GENERATED by scripts/catalog/codegen-catalog.mjs - do not edit */\n${typeExport}\nexport const ${name} = ${json} as const;\n\nexport const ${bySlug} = Object.fromEntries(\n  ${name}.map((item: { slug: string }) => [item.slug, item]),\n) as Record<string, (typeof ${name})[number]>;\n`;
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });

  const doorStyles = readJson("doorStyles.json");
  const finishes = readJson("finishes.json");
  const collections = readJson("collections.json");
  const cabinetProducts = readJson("cabinetProducts.json");
  const construction = readJson("construction.json");
  const panelBrands = readJson("panelBrands.json");

  fs.writeFileSync(path.join(OUT, "doorStyles.ts"), emitConst("DOOR_STYLES", "DoorStyle", doorStyles));
  fs.writeFileSync(path.join(OUT, "finishes.ts"), emitConst("FINISHES", "Finish", finishes));
  fs.writeFileSync(path.join(OUT, "collections.ts"), emitConst("COLLECTIONS", "CabinetCollection", collections));
  fs.writeFileSync(path.join(OUT, "cabinetProducts.ts"), emitConst("CABINET_PRODUCTS", "CabinetProduct", cabinetProducts));
  fs.writeFileSync(path.join(OUT, "construction.ts"), `/** AUTO-GENERATED */\nexport const OSC_CONSTRUCTION = ${JSON.stringify(construction, null, 2)} as const;\n`);
  fs.writeFileSync(path.join(OUT, "panelBrands.ts"), `/** AUTO-GENERATED */\nexport const PANEL_BRANDS = ${JSON.stringify(panelBrands, null, 2)} as const;\n`);

  const index = `/** AUTO-GENERATED barrel */\nexport { DOOR_STYLES, DOOR_STYLE_BY_SLUG } from "./doorStyles";\nexport { FINISHES, FINISH_BY_SLUG } from "./finishes";\nexport { COLLECTIONS, COLLECTION_BY_SLUG } from "./collections";\nexport { CABINET_PRODUCTS, CABINET_PRODUCT_BY_SLUG } from "./cabinetProducts";\nexport { OSC_CONSTRUCTION } from "./construction";\nexport { PANEL_BRANDS } from "./panelBrands";\n`;
  fs.writeFileSync(path.join(OUT, "index.ts"), index);

  console.log(`Generated catalog TS in ${OUT}`);
}

main();
