#!/usr/bin/env node
/**
 * Generate shared/catalog/generated/*.ts from data/catalog.json (single source of truth).
 *
 * catalog.json is the authoritative supplier extraction. This script derives the
 * customer-facing catalog shape the app consumes, stripping supplier/brand names
 * and raw SKU codes from anything that gets rendered.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const DATA = path.join(ROOT, "data/supplier-catalog");
const OUT = path.join(ROOT, "shared/catalog/generated");
const CATALOG_PATH = path.join(ROOT, "data/catalog.json");
const FINISH_IMG_DIR = path.join(ROOT, "public/images/catalog/finishes");
const finishImageExists = (file) => fs.existsSync(path.join(FINISH_IMG_DIR, file));

const catalog = JSON.parse(fs.readFileSync(CATALOG_PATH, "utf8"));

// Supplier cabinet line-drawing renderings ({ OSC_CODE: "/images/.../x.webp" }),
// extracted from the catalog PDF. Used as the product image when available.
const CABINET_RENDERINGS_PATH = path.join(DATA, "cabinetRenderings.json");
const cabinetRenderings = fs.existsSync(CABINET_RENDERINGS_PATH)
  ? JSON.parse(fs.readFileSync(CABINET_RENDERINGS_PATH, "utf8"))
  : {};
const renderingExists = (rel) => rel && fs.existsSync(path.join(ROOT, "public", rel.replace(/^\//, "")));

const DOOR_STYLE_IDS = [
  "slab",
  "three-piece",
  "modern-shaker",
  "thin-shaker",
  "alpha-shaker",
  "beta-shaker",
];

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function uniqueSlugger() {
  const seen = new Map();
  return (base) => {
    const b = base || "item";
    const n = (seen.get(b) || 0) + 1;
    seen.set(b, n);
    return n === 1 ? b : `${b}-${n}`;
  };
}

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(DATA, name), "utf8"));
}

function bySlugConst(arrayName) {
  const map = {
    FINISHES: "FINISH",
    DOOR_STYLES: "DOOR_STYLE",
    COLLECTIONS: "COLLECTION",
    CABINET_PRODUCTS: "CABINET_PRODUCT",
    ACCESSORY_FAMILIES: "ACCESSORY_FAMILY",
  };
  const base = map[arrayName] ?? (arrayName.endsWith("S") ? arrayName.slice(0, -1) : arrayName);
  return `${base}_BY_SLUG`;
}

function emitConst(name, typeName, data) {
  const json = JSON.stringify(data, null, 2);
  const bySlug = bySlugConst(name);
  return `/** AUTO-GENERATED by scripts/catalog/codegen-catalog.mjs - do not edit */\nimport type { ${typeName} } from "../types";\nexport type { ${typeName} } from "../types";\n\nexport const ${name}: ${typeName}[] = ${json};\n\nexport const ${bySlug} = Object.fromEntries(\n  ${name}.map((item) => [item.slug, item]),\n) as Record<string, ${typeName}>;\n`;
}

// ── Door styles ───────────────────────────────────────────────────────────────
function doorSlug(name) {
  if (name === "3 Piece") return "three-piece";
  return slugify(name);
}

const doorStyles = catalog.doorStyles.map((d) => {
  const slug = doorSlug(d.name);
  const woodOnly = slug === "three-piece";
  return {
    id: slug,
    slug,
    name: d.name,
    oscName: d.name,
    description: d.description,
    constructionNotes: `${d.description} Drawer fronts: ${d.drawerFront}.`,
    compatibleFinishCategories: woodOnly ? ["woodgrain"] : ["matte", "gloss", "woodgrain"],
    drawerFrontDefault: "slab",
    availableInCollections: ["custom"],
    imagePath: `/images/catalog/${d.image}`,
  };
});

// ── Finishes ──────────────────────────────────────────────────────────────────
const FAMILY_HEX = {
  Green: "#2D4A3E",
  "Neutral / Beige": "#D8CFC0",
  Black: "#1A1A1A",
  Grey: "#8A8A8A",
  Blue: "#3A5A78",
  White: "#F2EFE9",
  Wood: "#9C6B43",
};

// Neutral greige tile for finishes whose family is "Confirm from swatch" /
// unknown, so every swatch still renders a flat color (family stays unset).
const FAMILY_HEX_DEFAULT = "#CFC7B8";

function sheenFor(cat) {
  if (cat === "gloss") return "gloss";
  if (cat === "woodgrain") return "satin";
  return "matte";
}

function familyNorm(fam) {
  if (!fam || fam === "Confirm from swatch") return undefined;
  if (fam === "Neutral / Beige") return "Neutral";
  return fam;
}

// Names that appear in more than one category get disambiguated for display
// (e.g. "Morning Dew - Matte" vs "Morning Dew - Gloss").
const finishNameCounts = {};
for (const f of catalog.finishes) {
  finishNameCounts[f.name] = (finishNameCounts[f.name] || 0) + 1;
}

const finishSlug = uniqueSlugger();
const finishes = catalog.finishes.map((f) => {
  const cat = f.category.toLowerCase();
  const baseSlug = slugify(`${cat}-${f.name}`);
  const slug = finishSlug(baseSlug);
  const confirm = f.priceTier === "CONFIRM";
  const marker = confirm ? 3 : (f.priceTier.match(/\$/g) || []).length;
  const displayName = finishNameCounts[f.name] > 1 ? `${f.name} - ${f.category}` : f.name;
  const compatibleDoorStyleIds =
    cat === "woodgrain" ? [...DOOR_STYLE_IDS] : DOOR_STYLE_IDS.filter((id) => id !== "three-piece");
  const fam = familyNorm(f.colorFamily);
  // Only point at a real on-disk swatch; otherwise leave imagePath unset so the
  // UI renders a flat color tile instead of requesting a missing image.
  const swatchFile = [`${baseSlug}.webp`, `${slugify(f.name)}.webp`].find(finishImageExists);
  const out = {
    id: slug,
    slug,
    name: displayName,
    oscName: f.name,
    category: cat,
    sheen: sheenFor(cat),
    hexColor: FAMILY_HEX[f.colorFamily] ?? FAMILY_HEX_DEFAULT,
    panelBrand: "",
    panelSeries: "",
    sidedness: "double",
    priceTierMarker: marker,
    compatibleDoorStyleIds,
    compatibleCollectionIds: ["custom"],
    onSiteNow: f.onSiteNow === "Yes",
  };
  // Always bind an image, in priority order: a real on-disk photo, then the
  // generated raster swatch (woodgrain composite / matte+gloss tile), then the
  // flat SVG tile as a last resort — so no finish ever renders broken or flat.
  const generatedWebp = path.join(ROOT, "public/generated/finishes", `${slug}.webp`);
  out.imagePath = swatchFile
    ? `/images/catalog/finishes/${swatchFile}`
    : fs.existsSync(generatedWebp)
      ? `/generated/finishes/${slug}.webp`
      : `/generated/finishes/${slug}.svg`;
  if (confirm) out.priceConfirm = true;
  if (fam) out.colorFamily = fam;
  return out;
});

// ── Collections (single custom offering, no Reserve) ──────────────────────────
const collections = [
  {
    id: "custom",
    slug: "custom",
    name: "Custom Cabinets",
    tagline: "Built to order for your Treasure Valley home",
    description: "Full custom frameless cabinetry built to order for your space.",
    features: ["Any finish", "Full size range", '1/4" sizing increments'],
    leadTime: catalog.content.leadTime,
    priceTier: "premium",
    heroImage: "/images/catalog/collections/custom.webp",
    oscLine: "Built-to-order custom line",
  },
];

// ── Cabinets ──────────────────────────────────────────────────────────────────
const CAT_MAP = {
  Wall: "wall",
  Base: "base",
  Tall: "tall",
  Vanity: "vanity",
  "Floating Shelf": "floating-shelf",
  Hood: "hood",
  "Filler/Crown": "filler",
  "End Panel": "end-panel",
  Panel: "panel",
};

const CAT_LABEL = {
  wall: "Wall Cabinet",
  base: "Base Cabinet",
  tall: "Tall Cabinet",
  vanity: "Vanity Cabinet",
  "floating-shelf": "Floating Shelf",
  hood: "Range Hood Cover",
  filler: "Filler / Crown",
  "end-panel": "End Panel",
  panel: "Trim Panel",
};

const NO_CONFIG_NAME = new Set(["floating-shelf", "hood", "filler", "end-panel", "panel"]);

function decode(code) {
  const cfg = {};
  let doors = 0;
  let drawers = 0;
  let shelves;
  let rollouts = 0;
  let partitions = 0;
  for (const p of code.split(/[-_]/)) {
    let m;
    if (p === "FHD") {
      doors += 1;
    } else if ((m = p.match(/^(\d+)D$/))) {
      doors += +m[1];
    } else if ((m = p.match(/^(\d+)BD$/))) {
      drawers += +m[1];
    } else if ((m = p.match(/^(\d+)TD$/))) {
      drawers += +m[1];
    } else if ((m = p.match(/^(\d+)S$/))) {
      shelves = +m[1];
    } else if ((m = p.match(/^(\d+)ROT$/))) {
      rollouts += +m[1];
    } else if ((m = p.match(/^(\d+)PART$/))) {
      partitions += +m[1];
    }
  }
  if (doors) cfg.doors = doors;
  if (drawers) cfg.drawers = drawers;
  if (shelves !== undefined) cfg.shelves = shelves;
  if (rollouts) cfg.rollouts = rollouts;
  if (partitions) cfg.partitions = partitions;
  return cfg;
}

function dimOf(min, max) {
  const variable = min === "variable" || max === "variable";
  return {
    min: typeof min === "number" ? min : null,
    max: typeof max === "number" ? max : null,
    variable,
  };
}

function cabName(cat, cfg) {
  const base = CAT_LABEL[cat];
  if (NO_CONFIG_NAME.has(cat)) return base;
  const bits = [];
  if (cfg.doors) bits.push(`${cfg.doors} Door${cfg.doors > 1 ? "s" : ""}`);
  if (cfg.drawers) bits.push(`${cfg.drawers} Drawer${cfg.drawers > 1 ? "s" : ""}`);
  return bits.length ? `${base}, ${bits.join(" + ")}` : base;
}

// Derive the legacy `configuration` shape from the authoritative `attrs` object
// when present, falling back to SKU-token decoding for older data.
function configFromAttrs(attrs) {
  const cfg = {};
  const doors = attrs.doors ?? 0;
  const drawers = (attrs.drawers ?? 0) + (attrs.topDrawers ?? 0) + (attrs.bottomDrawers ?? 0);
  if (doors) cfg.doors = doors;
  if (drawers) cfg.drawers = drawers;
  if (attrs.shelves) cfg.shelves = attrs.shelves;
  if (attrs.rollouts) cfg.rollouts = attrs.rollouts;
  if (attrs.partitions) cfg.partitions = attrs.partitions;
  return cfg;
}

const cabSlug = uniqueSlugger();
const cabinetProducts = catalog.cabinets.map((c) => {
  const cat = CAT_MAP[c.category];
  const slug = cabSlug(slugify(c.code));
  const cfg = c.attrs ? configFromAttrs(c.attrs) : decode(c.code);
  const width = dimOf(c.minW, c.maxW);
  const height = dimOf(c.minH, c.maxH);
  const depth = dimOf(c.minD, c.maxD);
  const widthRange = {
    minInches: width.min ?? 0,
    maxInches: width.max ?? width.min ?? 0,
  };
  if (width.variable) widthRange.note = "Cut to fit";
  const out = {
    id: slug,
    slug,
    oscCode: c.code,
    name: cabName(cat, cfg),
    category: cat,
    description: `Custom ${CAT_LABEL[cat].toLowerCase()} built to fit your space.`,
    widthRange,
    dimensions: { width, height, depth },
    configuration: cfg,
    compatibleCollectionIds: ["custom"],
    compatibleDoorStyleIds: [...DOOR_STYLE_IDS],
  };
  if (c.attrs) out.attrs = c.attrs;
  // Prefer the real supplier line-drawing rendering; otherwise fall back to the
  // generated front-elevation SVG box diagram under /public/generated/.
  const rendering = cabinetRenderings[c.code];
  out.boxImage = renderingExists(rendering)
    ? rendering
    : c.boxImage
      ? `/generated/${c.boxImage}`
      : `/generated/cabinets/${slug}.svg`;
  return out;
});

// ── Accessories (exactly the catalog families) ────────────────────────────────
const ACC_SLUG = {
  "Roll-Out Tray": "rollout-tray",
  "Trash Pull-Out": "trash-pullout",
  "Lazy Susan": "lazy-susan",
  "Blind Corner Pull-Out": "blind-corner",
  "Vertical Partition": "partition",
  "Floating Shelf": "floating-shelf",
};

const ACC_META = {
  "Roll-Out Tray": {
    category: "storage",
    description: "Full-extension roll-out trays that bring the back of the cabinet to you.",
  },
  "Trash Pull-Out": {
    category: "waste",
    description: "Hidden waste and recycling bins on a smooth pull-out.",
  },
  "Lazy Susan": {
    category: "storage",
    description: "Rotating corner shelves that make deep corners easy to reach.",
  },
  "Blind Corner Pull-Out": {
    category: "storage",
    description: "Pull-out hardware that rescues the hard-to-reach blind corner.",
  },
  "Vertical Partition": {
    category: "organization",
    description: "Upright dividers for trays, sheet pans, and cutting boards.",
  },
  "Floating Shelf": {
    category: "specialty",
    description: "Wall-mounted open shelving for a lighter, airy look.",
  },
};

// ── Site-wide content (warranty / lead time / disclaimer) ─────────────────────
// Only customer-facing fields; internal *Note and full-page fields are excluded.
const content = {
  warrantyHeadline: catalog.content.warrantyHeadline,
  warrantySummary: catalog.content.warrantySummary,
  leadTime: catalog.content.leadTime,
  estimateDisclaimer: catalog.content.estimateDisclaimer,
};
if (catalog.content.warrantyNote) content.warrantyNote = catalog.content.warrantyNote;
if (catalog.content.leadTimeNote) content.leadTimeNote = catalog.content.leadTimeNote;
if (catalog.content.warrantyFullPage) content.warrantyFullPage = catalog.content.warrantyFullPage;

const accessoryFamilies = catalog.accessories.map((a) => {
  const slug = ACC_SLUG[a.name] ?? slugify(a.name);
  const meta = ACC_META[a.name] ?? { category: "storage", description: "" };
  return {
    id: slug,
    slug,
    name: a.name,
    category: meta.category,
    oscCodePattern: "",
    description: meta.description,
    exampleSkus: [],
  };
});

function main() {
  fs.mkdirSync(OUT, { recursive: true });

  fs.writeFileSync(path.join(OUT, "doorStyles.ts"), emitConst("DOOR_STYLES", "DoorStyle", doorStyles));
  fs.writeFileSync(path.join(OUT, "finishes.ts"), emitConst("FINISHES", "Finish", finishes));
  fs.writeFileSync(path.join(OUT, "collections.ts"), emitConst("COLLECTIONS", "CabinetCollection", collections));
  fs.writeFileSync(
    path.join(OUT, "cabinetProducts.ts"),
    emitConst("CABINET_PRODUCTS", "CabinetProduct", cabinetProducts),
  );
  fs.writeFileSync(
    path.join(OUT, "accessoryFamilies.ts"),
    emitConst("ACCESSORY_FAMILIES", "AccessoryFamily", accessoryFamilies),
  );

  fs.writeFileSync(
    path.join(OUT, "content.ts"),
    `/** AUTO-GENERATED by scripts/catalog/codegen-catalog.mjs - do not edit */\nimport type { CatalogContent } from "../types";\nexport type { CatalogContent } from "../types";\n\nexport const CATALOG_CONTENT: CatalogContent = ${JSON.stringify(content, null, 2)};\n`,
  );

  if (catalog.nomenclature) {
    fs.writeFileSync(
      path.join(OUT, "nomenclature.ts"),
      `/** AUTO-GENERATED by scripts/catalog/codegen-catalog.mjs - do not edit */\nimport type { CatalogNomenclature } from "../types";\nexport type { CatalogNomenclature } from "../types";\n\nexport const CATALOG_NOMENCLATURE: CatalogNomenclature = ${JSON.stringify(catalog.nomenclature, null, 2)};\n`,
    );
  }

  // Construction / panel / hardware spec stay sourced from supplier extraction files.
  const construction = readJson("construction.json");
  const panelBrands = readJson("panelBrands.json");
  fs.writeFileSync(
    path.join(OUT, "construction.ts"),
    `/** AUTO-GENERATED */\nexport const OSC_CONSTRUCTION = ${JSON.stringify(construction, null, 2)} as const;\n`,
  );
  fs.writeFileSync(
    path.join(OUT, "panelBrands.ts"),
    `/** AUTO-GENERATED */\nexport const PANEL_BRANDS = ${JSON.stringify(panelBrands, null, 2)} as const;\n`,
  );

  const hardwareSpecPath = path.join(DATA, "hardwareSpec.json");
  let hardwareExport = "";
  if (fs.existsSync(hardwareSpecPath)) {
    const hardwareSpec = readJson("hardwareSpec.json");
    fs.writeFileSync(
      path.join(OUT, "hardwareSpec.ts"),
      `/** AUTO-GENERATED */\nexport const OSC_HARDWARE_SPEC = ${JSON.stringify(hardwareSpec, null, 2)} as const;\n`,
    );
    hardwareExport = `export { OSC_HARDWARE_SPEC } from "./hardwareSpec";\n`;
  }

  const nomenclatureExport = catalog.nomenclature
    ? `export { CATALOG_NOMENCLATURE } from "./nomenclature";\nexport type { CatalogNomenclature } from "./nomenclature";\n`
    : "";

  const index = `/** AUTO-GENERATED barrel */\nexport { DOOR_STYLES, DOOR_STYLE_BY_SLUG } from "./doorStyles";\nexport { FINISHES, FINISH_BY_SLUG } from "./finishes";\nexport { COLLECTIONS, COLLECTION_BY_SLUG } from "./collections";\nexport { CABINET_PRODUCTS, CABINET_PRODUCT_BY_SLUG } from "./cabinetProducts";\nexport { OSC_CONSTRUCTION } from "./construction";\nexport { PANEL_BRANDS } from "./panelBrands";\nexport { ACCESSORY_FAMILIES, ACCESSORY_FAMILY_BY_SLUG } from "./accessoryFamilies";\nexport { CATALOG_CONTENT } from "./content";\nexport type { CatalogContent } from "./content";\n${nomenclatureExport}${hardwareExport}`;
  fs.writeFileSync(path.join(OUT, "index.ts"), index);

  console.log(
    `Generated catalog TS: ${doorStyles.length} doors, ${finishes.length} finishes, ${collections.length} collection, ${cabinetProducts.length} cabinets, ${accessoryFamilies.length} accessories`,
  );
}

main();
