'use client';
import {useState} from 'react';
import {ArrowUpRight,ArrowRight,Phone,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {FAQSection} from '@/components/FAQSection';
import {TestimonialsSection} from '@/components/sections/TestimonialsSection';
import {ApprovedEstimate} from './ApprovedEstimate';
import {steps,differentiators,additionalRooms,doorStyles} from './cabinet-content';
const rooms = [
 {name:'Kitchen',title:'The heart of your home.',image:'kitchen.webp',desc:'Base cabinets, uppers, pantries, and appliance panels designed as one coordinated kitchen.',details:'Bring storage, appliances, and everyday routines into one thoughtful layout. Explore pantry cabinets, deep drawers, island storage, and finishes that work together.',features:['Storage planned around the way you cook','Coordinated island and perimeter cabinetry','Door, finish, and hardware selections']},
 {name:'Bathroom',title:'A better start to your day.',image:'bathroom.webp',desc:'Vanities and drawer storage sized for your daily routine, with moisture-resistant options.',details:'Make your bathroom easier to use with a vanity planned around your space, storage needs, and plumbing. Coordinate drawer layouts, door styles, and finishes with the rest of the room.',features:['Single and double vanity configurations','Storage that keeps counters clear','Finish guidance for your room']},
 {name:'Mudroom & built-ins',title:'Less clutter. More living.',image:'mudroom.webp',desc:'Bench seating, boot storage, and built-ins that make hardworking spaces feel considered.',details:'Put hardworking storage where you need it. Plan entry benches, laundry cabinetry, home office built-ins, entertainment storage, and custom pantry layouts.',features:['Storage sized to your room','Coordinated cabinetry throughout your home','Practical layouts for everyday routines']}
];
const finishes=[{name:'Bitter',family:'Warm neutral',image:'bitter.webp'},{name:'Macaron Green',family:'Soft color',image:'green.webp'},{name:'Brezee Beige',family:'Light neutral',image:'beige.webp'},{name:'Pearl Black',family:'Deep contrast',image:'black.webp'}];

export function ApprovedHome(){const [finish,setFinish]=useState<number|null>(null);const [door,setDoor]=useState('Help me choose');return <div className="cabinet-approved">
  <section className="hero" aria-labelledby="hero-title">
   <img className="hero-image" src="/images/approved/hero-p5-v2.webp" srcSet="/images/approved/hero-mobile.webp 960w, /images/approved/hero-p5-v2.webp 1672w" sizes="100vw" alt="Kitchen with natural white oak cabinetry, cream shaker cabinets, ivory stone, and bronze details" width="1672" height="941" fetchPriority="high"/>
   <div className="hero-shade"/>
   <div className="hero-content"><p className="eyebrow"><span/> CUSTOM CABINETRY · TREASURE VALLEY, IDAHO</p><h1 id="hero-title">Idaho’s premier<br/><em>cabinet company.</em></h1><p>Premium custom cabinets, designed, built, and installed by one accountable team. From the first sketch to the final walkthrough.</p><div className="hero-actions"><a className="button" href="/estimate">Get my online estimate <ArrowUpRight size={20}/></a><a className="text-link light" href="#cabinetry">Browse custom cabinets <ArrowRight size={18}/></a></div><div className="hero-reassurance"><span><Check size={15}/> Get a preliminary estimate online</span><span><Check size={15}/> Bonded & insured</span></div></div>
   <div className="hero-bottom"><span>Designed around your life. Built around your space.</span><a href="#cabinetry">SCROLL TO EXPLORE <ArrowRight size={16}/></a></div>

  </section>
  <section className="proof-bar" aria-label="The Boise Cabinet Co difference"><div><strong>299</strong><span>Finish options</span></div><div><strong>6</strong><span>Door styles</span></div><div><strong>Free</strong><a href="#contact">In-home design consultation <ArrowUpRight size={14}/></a></div><div><strong>Lifetime</strong><a href="/warranty">Limited warranty · View terms <ArrowUpRight size={14}/></a></div></section>
  <section id="cabinetry" className="section wrap room-editorial">
 <div className="section-heading"><div><p className="eyebrow">CABINETRY, CONSIDERED</p><h2>Every room.<br/><em>Considered.</em></h2></div><p>Custom kitchen cabinets, bathroom vanities, and built-in storage. Choose your door style, finish, and hardware. We bring the layout, fabrication, and installation together.</p></div>
 <Tabs defaultValue="kitchen" className="room-explorer"><TabsList className="room-tabs"><TabsTrigger value="kitchen">Kitchens</TabsTrigger><TabsTrigger value="bathroom">Bathrooms</TabsTrigger><TabsTrigger value="storage">Built-ins</TabsTrigger><TabsTrigger value="more">More rooms</TabsTrigger></TabsList>
 {rooms.map((r,i)=><TabsContent key={r.name} value={['kitchen','bathroom','storage'][i]}><div className="room-scene"><button className="room-scene-image" onClick={()=>window.location.assign(["/cabinets/kitchen","/cabinets/bathroom","/cabinets/mudroom"][i])} aria-label={'Explore '+r.name.toLowerCase()+' cabinetry'}><img src={'/images/approved/'+r.image} alt={r.name+' cabinetry'} loading="lazy" width="1080" height="810"/><span className="scene-explore">Explore this space <ArrowUpRight size={18}/></span></button><div className="room-scene-copy"><span className="eyebrow">0{i+1} / {r.name}</span><h3>{r.title}</h3><p>{r.desc}</p><button className="text-link" onClick={()=>window.location.assign(["/cabinets/kitchen","/cabinets/bathroom","/cabinets/mudroom"][i])}>Explore {r.name.toLowerCase()} <ArrowUpRight size={18}/></button></div></div></TabsContent>)}
 <TabsContent value="more"><div className="room-scene"><div className="room-scene-image"><img src="/images/approved/laundry-charcoal.webp" alt="Laundry cabinetry with charcoal cabinets and oak shelving" loading="lazy" width="1448" height="1086"/></div><div className="room-scene-copy"><span className="eyebrow">THINK BEYOND THE KITCHEN</span><h3>Every inch.<br/>Put to good use.</h3><Accordion type="single" collapsible className="other-room-list">{additionalRooms.map(([name,desc,url])=><AccordionItem value={name} key={name}><AccordionTrigger>{name}</AccordionTrigger><AccordionContent><p>{desc}</p><a className="text-link" href={''+url}>Explore {name.toLowerCase()} <ArrowUpRight size={16}/></a></AccordionContent></AccordionItem>)}</Accordion></div></div></TabsContent>
 </Tabs></section>
  <ApprovedEstimate/>
  <section id="finishes" className="finish-section">
   <div className="finish-photo"><img src="/images/approved/design-optimized.webp" alt="Cabinet door samples, finish swatches, and kitchen design plans" loading="lazy" width="1536" height="1024"/><div className="photo-label"><span>THE DETAILS MAKE IT YOURS.</span><span>Design & selections</span></div></div>
   <div className="finish-copy"><p className="eyebrow">FIND YOUR POINT OF VIEW</p><h2>A little texture.<br/>A little contrast.<br/><em>All you.</em></h2><p>299 finishes. Six door styles. Matte solids, high-gloss colors, and woodgrain textures. Find the combination that makes your home feel like you.</p>
   <Tabs defaultValue="finishes"><TabsList className="selection-tabs"><TabsTrigger value="finishes">Explore finishes</TabsTrigger><TabsTrigger value="doors">Door styles</TabsTrigger></TabsList><TabsContent value="finishes"><div className="swatches">{finishes.map((f,i)=><button key={f.name} onClick={()=>setFinish(i)} aria-label={`Select ${f.name}`} aria-pressed={finish===i} className={finish===i?'selected':''}><img src={'/images/approved/'+f.image} alt="" width="100" height="100"/>{finish===i&&<span><Check size={14}/></span>}</button>)}</div><div className="swatch-info" aria-live="polite"><b>{finish===null?'Find your finish':finishes[finish].name}</b><span>{finish===null?'Select a sample to explore':finishes[finish].family}</span></div><p className="sample-note">Explore a selection from our catalog. Confirm your finish with a physical sample.</p></TabsContent><TabsContent value="doors"><RadioGroup value={door} onValueChange={setDoor} className="door-choices" aria-label="Door style preference">{doorStyles.map(d=><label key={d}><RadioGroupItem value={d}/><span>{d}</span></label>)}</RadioGroup><p className="sample-note">Six profiles, from clean slab doors to distinctive shaker details. We’ll help you compare the construction and proportions.</p></TabsContent></Tabs>
   <div className="finish-links"><a className="text-link light" href="/catalog">Explore the full catalog <ArrowUpRight size={18}/></a></div></div>
  </section>
  <section id="why-us" className="why-section section"><div className="wrap why-layout"><div className="sticky-intro"><p className="eyebrow">WHY BOISE CABINET CO</p><h2>Great cabinets.<br/><em>A better experience.</em></h2><p>One accountable team. A written scope before fabrication. A job site that respects your home. We built our process around the things homeowners should be able to count on.</p></div><Accordion type="single" collapsible defaultValue="standard-0" className="standard-accordion">{differentiators.map(([title,desc],i)=><AccordionItem value={"standard-"+i} key={title}><AccordionTrigger>{title}</AccordionTrigger><AccordionContent>{desc}</AccordionContent></AccordionItem>)}</Accordion></div><div className="value-panel wrap"><figure className="value-photo"><img src="/images/approved/kitchen-charcoal.webp" alt="Kitchen combining charcoal cabinetry, a white oak island, and ivory stone" loading="lazy" width="1672" height="941"/><figcaption>CHARCOAL & OAK</figcaption></figure><div className="value-copy"><p className="eyebrow">WHERE YOUR MONEY GOES</p><h2>Don’t pay for our overhead.<br/><em>Pay for the cabinets.</em></h2><p>Big offices, fancy showrooms, truck fleets, and layers of management add cost. We keep our shop lean so more of your budget goes into skilled craftsmanship, better materials, and the cabinetry in your home.</p><a className="text-link" href="/estimate">Get my online estimate <ArrowUpRight size={18}/></a></div></div></section>
  <section id="process" className="section wrap process-editorial"><div className="process-overview"><p className="eyebrow">FROM IDEA TO INSTALLATION</p><h2>A clear plan.<br/><em>At every step.</em></h2><p>Design, build, and installation with one team. Know what happens next, what needs your approval, and where your project stands.</p><a className="text-link" href="/portal">Your project portal <ArrowUpRight size={18}/></a></div><Accordion type="single" collapsible defaultValue="step-0" className="process-accordion">{steps.map((s,i)=><AccordionItem value={'step-'+i} key={s.tag}><AccordionTrigger><span className="process-index">0{i+1}</span><span>{s.title}</span></AccordionTrigger><AccordionContent><p>{s.desc}</p></AccordionContent></AccordionItem>)}</Accordion></section>
  <section id="inspiration" className="craft-section"><div className="craft-photo"><img src="/images/approved/drawer-oak.webp" alt="Natural oak drawer and organized utensil storage" loading="lazy" width="1448" height="1086"/><span className="craft-caption">THE BEAUTY IS IN THE EVERYDAY DETAILS</span></div><div className="craft-copy"><p className="eyebrow">GOOD DESIGN GOES DEEPER</p><h2>Beautiful outside.<br/><em>Thoughtful inside.</em></h2><p>Frameless Euro construction. Soft-close hardware. Hand-checked finishes. Made to order for everyday life.</p><Accordion type="single" collapsible className="craft-details"><AccordionItem value="construction"><AccordionTrigger>Frameless construction</AccordionTrigger><AccordionContent>Clean lines and accessible storage, made to fit your space. <a href="/construction">See how we build.</a></AccordionContent></AccordionItem><AccordionItem value="hardware"><AccordionTrigger>Hardware you feel every day</AccordionTrigger><AccordionContent>Soft-close doors and full-extension drawer storage, with selections coordinated around your routines.</AccordionContent></AccordionItem><AccordionItem value="warranty"><AccordionTrigger>A limited lifetime warranty</AccordionTrigger><AccordionContent>Workmanship and material coverage for the original homeowner. Conditions and exclusions apply. <a href="/warranty">View warranty terms.</a></AccordionContent></AccordionItem></Accordion><button className="text-link" onClick={()=>window.location.assign("/catalog")}>Explore design inspiration <ArrowUpRight size={18}/></button></div></section>
  <TestimonialsSection limit={3} showViewAll={true}/>
  <section className="builder-band wrap"><div><p className="eyebrow">FOR BUILDERS, REMODELERS & DESIGNERS</p><h2>Your plans.<br/><em>Our cabinet expertise.</em></h2></div><div><p>One home or a full project pipeline. Let’s coordinate the cabinet package, selections, and installation scope around your plans.</p><a className="button dark" href="/estimate">Get my online estimate <ArrowUpRight size={18}/></a><button className="text-link estimate-secondary" onClick={()=>window.location.assign("/builders")}>Let’s work together <ArrowUpRight size={18}/></button></div></section>
  <FAQSection/>
  <section id="contact" className="consultation-section"><div className="wrap consultation-layout"><div className="consultation-copy"><p className="eyebrow">YOUR HOME. YOUR NEXT CHAPTER.</p><h2>Let’s make room<br/><em>for your ideas.</em></h2><p>Start with an online estimate for your cabinetry. Then arrange a free in-home design consultation to work through the details.</p><a className="button" href="/estimate">Get my online estimate <ArrowUpRight size={18}/></a><a className="estimate-secondary" href="/contact">Book a free consultation <ArrowUpRight size={18}/></a><a className="consultation-phone" href="tel:+12084771169">Prefer to talk? (208) 477-1169</a></div><div className="consultation-outline"><p className="eyebrow">WHAT TO EXPECT</p><h3>A useful conversation.<br/>No pressure.</h3><ul><li><Check size={18}/> 60–90 minutes in your home</li><li><Check size={18}/> Layout, collection, finish, and door guidance</li><li><Check size={18}/> A planning investment range</li><li><Check size={18}/> No obligation to move forward</li></ul><div className="consultation-location"><p>Meridian, Idaho · Serving the Treasure Valley</p><a href="mailto:hello@boisecabinet.co">hello@boisecabinet.co</a><a href="sms:+12084771169">Send us a text <ArrowUpRight size={15}/></a></div></div></div></section>
 </div>;}
