import type { BlogPostData } from '../blogContent';
import { expandCluster } from './contentFactory';
import { guidePath } from '../contentHubs';

function legacyBody(
  slug: string,
  hubSlug: string,
  intro: string,
  sections: string,
  pillar: string,
): string {
  return expandCluster(
    `${intro}${sections}<p>Related: <a href="${pillar}">hub guide</a> · <a href="/guides/boise-remodeling-cost-guide">costs</a> · <a href="/guides/treasure-valley-remodeling-guide">Treasure Valley</a>.</p>`,
    slug,
    hubSlug,
    118,
  );
}

export const LEGACY_BLOG_POSTS: BlogPostData[] = [
  {
    slug: 'ada-vs-canyon-county-permit-timelines',
    title: 'Ada vs Canyon County Remodel Permits: Timelines Homeowners Should Know',
    seoTitle: 'Ada vs Canyon County Remodel Permit Timelines',
    metaDescription:
      'How Ada County and Canyon County permit timelines differ for kitchen, bath, and addition remodels in the Treasure Valley.',
    excerpt:
      'Permit timelines vary by county, project type, and whether structural or MEP plans are required.',
    author: 'Boise Remodeling Co',
    category: 'Remodeling Process',
    hubSlug: 'remodeling-process',
    tags: ['permits', 'ada county', 'canyon county'],
    publishedAt: '2026-02-05',
    relatedLinks: [
      { url: guidePath('boise-remodeling-process-guide') },
      { url: '/blog/boise-permit-guide' },
      { url: '/areas/boise' },
      { url: '/areas/nampa' },
    ],
    faqs: [
      { question: 'Who pulls permits on a design-build remodel?', answer: 'Boise Remodeling Co includes permits in scope for Ada and Canyon County projects.' },
      { question: 'How long do Ada County kitchen permits take?', answer: 'Layout changes often need several weeks of plan review.' },
      { question: 'Is Canyon County different?', answer: 'Yes—portals and review cadence differ from Ada County.' },
      { question: 'Do you serve Nampa and Caldwell?', answer: 'Yes—we coordinate Canyon County permits.' },
      { question: 'Can construction start before permits?', answer: 'No—approved permits are required for covered work.' },
      { question: 'What plans are required?', answer: 'Structural and MEP sheets are common for layout changes.' },
      { question: 'How do I schedule around permits?', answer: 'Build permit lead time into your master schedule.' },
      { question: 'Where is the full process guide?', answer: 'See our Boise Remodeling Process Guide and permit articles.' },
    ],
    content: legacyBody(
      'ada-vs-canyon-county-permit-timelines',
      'remodeling-process',
      `<p>Whether your home is in <a href="/areas/boise">Boise</a> (Ada County) or <a href="/areas/nampa">Nampa</a> and <a href="/areas/caldwell">Caldwell</a> (Canyon County), permit lead time belongs in your schedule.</p>`,
      `<h2>Ada County</h2><p>Cosmetic updates may move quickly; layout changes need plan review in Meridian, Eagle, Kuna, and Star as well.</p><h2>Canyon County</h2><p>Additions and structural work extend timelines in Nampa and Middleton.</p>`,
      guidePath('boise-remodeling-process-guide'),
    ),
    quickAnswer: 'Ada County and Canyon County use different permit portals and review timelines—layout and structural remodels often need weeks of plan review in both.',
    keyTakeaways: ['Build permits into the schedule', 'Ada vs Canyon processes differ', 'Design-build teams coordinate submissions'],
    wordCountTarget: 'cluster',
  },
  {
    slug: 'how-to-choose-design-build-contractor',
    title: 'How to Choose a Design-Build Remodeling Contractor in Boise',
    seoTitle: 'How to Choose a Design-Build Contractor Boise',
    metaDescription:
      'Checklist for choosing a design-build remodeling contractor in Boise: scope, communication, licenses, and red flags.',
    excerpt: 'The best fit is not always the lowest bid—look for written scope and one accountable team.',
    author: 'Boise Remodeling Co',
    category: 'Contractor Selection',
    hubSlug: 'contractor-selection',
    tags: ['contractor', 'design-build', 'boise'],
    publishedAt: '2026-02-18',
    relatedLinks: [
      { url: guidePath('choose-remodeling-contractor-boise') },
      { url: '/about' },
      { url: '/contact' },
    ],
    faqs: [
      { question: 'What is design-build?', answer: 'Design, estimating, and construction under one contract.' },
      { question: 'Should I get multiple bids?', answer: 'Yes—with aligned scope and allowances.' },
      { question: 'What are red flags?', answer: 'Vague scope and large upfront cash demands.' },
      { question: 'Are you licensed?', answer: 'License details available upon request.' },
      { question: 'Who is my contact during build?', answer: 'A dedicated project manager.' },
      { question: 'Do you handle permits?', answer: 'Yes for Ada and Canyon County scope.' },
      { question: 'How do I start?', answer: 'Schedule a consultation.' },
      { question: 'See the full contractor guide?', answer: 'Read our Choose a Remodeling Contractor in Boise pillar.' },
    ],
    content: legacyBody(
      'how-to-choose-design-build-contractor',
      'contractor-selection',
      `<p>Design-build reduces finger-pointing between designer and builder. Start with <a href="${guidePath('choose-remodeling-contractor-boise')}">our contractor guide</a>.</p>`,
      `<h2>Questions to ask</h2><ul><li>Written scope before construction?</li><li>Single point of contact?</li><li>Permit handling?</li><li>Warranty terms?</li></ul>`,
      guidePath('choose-remodeling-contractor-boise'),
    ),
    quickAnswer: 'Choose a Boise design-build remodeler with written scope, local permits experience, clear communication, and aligned bids—not price alone.',
    keyTakeaways: ['Compare aligned scopes', 'Design-build improves accountability', 'Verify insurance and references'],
    wordCountTarget: 'cluster',
  },
  {
    slug: 'whole-home-remodel-planning-checklist',
    title: 'Whole-Home Remodel Planning Checklist for Treasure Valley Homeowners',
    seoTitle: 'Whole-Home Remodel Planning Checklist Idaho',
    metaDescription:
      'Room-by-room checklist for whole-home remodels: sequencing, temporary living, contingency, and design-build.',
    excerpt: 'Whole-home remodels succeed when sequencing and contingency are decided early.',
    author: 'Boise Remodeling Co',
    category: 'Whole Home Remodeling',
    hubSlug: 'whole-home-remodeling',
    tags: ['whole-home', 'checklist', 'meridian'],
    publishedAt: '2026-03-01',
    relatedLinks: [
      { url: guidePath('whole-home-remodeling-guide') },
      { url: '/blog/whole-home-remodel-cost-boise' },
      { url: '/services/whole-home-remodel/meridian' },
    ],
    faqs: [
      { question: 'What to plan first?', answer: 'Must-have rooms and structural/MEP priorities.' },
      { question: 'How much contingency?', answer: '10–15% for concealed conditions.' },
      { question: 'Can I live during construction?', answer: 'Phasing or temporary housing may be needed.' },
      { question: 'How long?', answer: 'Often 4–12 months depending on scope.' },
      { question: 'One contractor?', answer: 'Design-build coordinates trades.' },
      { question: 'Permits?', answer: 'Included in our scope when required.' },
      { question: 'Budget help?', answer: 'See whole-home cost article and cost guide.' },
      { question: 'Remodel vs move?', answer: 'Read our remodeling vs moving article.' },
    ],
    content: legacyBody(
      'whole-home-remodel-planning-checklist',
      'whole-home-remodeling',
      `<p>Treat whole-home work as one program across Boise, Meridian, Eagle, Kuna, Star, Middleton, Nampa, and Caldwell.</p>`,
      `<h2>Checklist</h2><ol><li>Define must-have rooms</li><li>Lock structural/MEP</li><li>Plan temporary living</li><li>Hold 10–15% contingency</li></ol>`,
      guidePath('whole-home-remodeling-guide'),
    ),
    quickAnswer: 'Whole-home remodel planning requires phased scope, early structural decisions, contingency, and realistic timelines across the Treasure Valley.',
    keyTakeaways: ['One master program', 'Contingency for unknowns', 'Sequence before finishes'],
    wordCountTarget: 'cluster',
  },
  {
    slug: 'room-addition-guide-treasure-valley',
    title: 'Room Addition Guide: Matching Your Home in the Treasure Valley',
    seoTitle: 'Room Addition Guide Boise Treasure Valley',
    metaDescription:
      'Room additions in Boise, Eagle, Kuna: setbacks, architecture, foundation, and timelines.',
    excerpt: 'Additions that look original need early design and realistic permits.',
    author: 'Boise Remodeling Co',
    category: 'Home Additions',
    hubSlug: 'home-additions',
    tags: ['addition', 'eagle', 'kuna'],
    publishedAt: '2026-03-12',
    relatedLinks: [
      { url: guidePath('boise-home-addition-guide') },
      { url: '/blog/home-addition-cost-boise' },
      { url: '/services/room-addition/eagle' },
    ],
    faqs: [
      { question: 'How much does an addition cost?', answer: 'Often $80,000–$250,000+ depending on scope—see our cost article.' },
      { question: 'Permits required?', answer: 'Yes for structural work in Ada and Canyon County.' },
      { question: 'Match existing home?', answer: 'Design-build coordinates roof and exterior.' },
      { question: 'HOA in Eagle?', answer: 'Many neighborhoods require design review.' },
      { question: 'Second story?', answer: 'Feasibility depends on foundation and framing.' },
      { question: 'Timeline?', answer: 'Often 4–9 months including design and permits.' },
      { question: 'ADUs?', answer: 'See ADU guide and service page.' },
      { question: 'Cities served?', answer: 'All major Treasure Valley cities.' },
    ],
    content: legacyBody(
      'room-addition-guide-treasure-valley',
      'home-additions',
      `<p>Additions in <a href="/services/room-addition/eagle">Eagle</a> and <a href="/services/room-addition/kuna">Kuna</a> may need HOA review plus county permits.</p>`,
      `<h2>Design-build for additions</h2><p>Foundation and roof tie-in should be resolved in design.</p>`,
      guidePath('boise-home-addition-guide'),
    ),
    quickAnswer: 'Treasure Valley room additions need feasibility on setbacks and structure, matching architecture, and Ada or Canyon permits—often $80k–$250k+.',
    keyTakeaways: ['Feasibility first', 'HOA time in Eagle', 'One design-build contract'],
    wordCountTarget: 'cluster',
  },
];
