/**
 * Generates the generic top-down floor-plan diagrams (SVG) for each cabinet layout.
 *
 * Outputs:
 *  - public/images/catalog/layouts/<slug>.svg  (static assets)
 *  - shared/catalog/generated/layoutDiagrams.ts (LAYOUT_DIAGRAM_SVG markup map)
 *
 * These generic 4:3 diagrams are used by the Project Estimator ("Pick your
 * layout"), which inlines them via LAYOUT_DIAGRAM_SVG and recolors the cabinet
 * runs through the --cab-* CSS custom properties. The Design Studio renders its
 * own diagrams at the homeowner's scanned room proportions via
 * lib/design/layoutDiagram.ts (same geometry, different aspect ratio). Re-run
 * after changing a layout:
 *   npx tsx scripts/generate-layout-diagrams.ts
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildLayoutDiagram, LAYOUT_DIAGRAM_SLUGS } from "../lib/design/layoutDiagram";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../public/images/catalog/layouts");

mkdirSync(OUT_DIR, { recursive: true });
const svgBySlug: Record<string, string> = {};
let count = 0;
for (const slug of LAYOUT_DIAGRAM_SLUGS) {
  const { svg } = buildLayoutDiagram(slug);
  svgBySlug[slug] = svg;
  writeFileSync(resolve(OUT_DIR, `${slug}.svg`), svg + "\n", "utf8");
  count++;
}
console.log(`Wrote ${count} layout diagrams to ${OUT_DIR}`);

// Also emit the raw SVG markup as a TS module so the estimator can inline the
// diagrams (instead of loading them via <img>) and recolor the cabinet runs
// through the --cab-* CSS custom properties without re-fetching anything.
const MODULE_OUT = resolve(
  __dirname,
  "../shared/catalog/generated/layoutDiagrams.ts",
);
const entries = Object.entries(svgBySlug)
  .map(([slug, svg]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(svg)},`)
  .join("\n");
const module = `/** AUTO-GENERATED by scripts/generate-layout-diagrams.ts - do not edit */
export const LAYOUT_DIAGRAM_SVG: Record<string, string> = {
${entries}
};
`;
writeFileSync(MODULE_OUT, module, "utf8");
console.log(`Wrote layout diagram markup module to ${MODULE_OUT}`);
