import fs from "fs";
import path from "path";
import { Metadata } from "next";
import { notFound } from "next/navigation";
import { BLOG_POSTS } from "@/shared/blogContent";
import {
  generateArticleSchema,
  generateBreadcrumbSchema,
  generateFAQSchema,
  generateSpeakableSchema,
} from "@/lib/schema";
import { buildCanonical } from "@/lib/page-metadata";
import { BlogPostLayout } from "@/components/marketing/BlogPostLayout";
import {
  getAbsoluteImageUrl,
  getBlogHeroImage,
  getBlogImageAlt,
} from "@/shared/blogImages";
import { clampMetaDescription, getBaseUrl } from "@/lib/seo";
import { SITE_CONFIG } from "@/shared/siteConfig";
import { CONTENT_HUBS, categoryHubPath } from "@/shared/contentHubs";

export async function generateStaticParams() {
  return BLOG_POSTS.map((post) => ({
    slug: post.slug,
  }));
}

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const post = BLOG_POSTS.find((p) => p.slug === params.slug);

  if (!post) {
    return { title: "Post Not Found" };
  }

  const rawTitle = post.seoTitle || post.title;
  const brandSuffix = ` | ${SITE_CONFIG.name}`;
  const title = rawTitle.endsWith(brandSuffix)
    ? rawTitle.slice(0, -brandSuffix.length)
    : rawTitle;
  const description = clampMetaDescription(post.metaDescription || post.excerpt);
  const heroPath = getBlogHeroImage(post.slug, post.heroImage);
  const imageUrl = getAbsoluteImageUrl(heroPath, getBaseUrl());
  const imageAlt = getBlogImageAlt(post.slug);

  // Branded social-share card (photo + dark overlay + seal + title) generated by
  // scripts/generate-og-images.ts into public/images/og/{slug}.png. Falls back to
  // the hero image until a post's card has been generated.
  const ogFile = path.join(process.cwd(), "public", "images", "og", `${post.slug}.jpg`);
  const shareImageUrl = fs.existsSync(ogFile)
    ? getAbsoluteImageUrl(`/images/og/${post.slug}.jpg`, getBaseUrl())
    : imageUrl;

  return {
    title,
    description,
    alternates: {
      canonical: buildCanonical(`/blog/${post.slug}`),
    },
    openGraph: {
      title: `${title} | ${SITE_CONFIG.name} Blog`,
      description,
      url: buildCanonical(`/blog/${post.slug}`),
      type: "article",
      publishedTime: post.publishedAt,
      images: [{ url: shareImageUrl, width: 1200, height: 630, alt: `${title} - ${SITE_CONFIG.name}` }],
      siteName: SITE_CONFIG.name,
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | ${SITE_CONFIG.name} Blog`,
      description,
      images: [shareImageUrl],
    },
  };
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export default function BlogPostPage({ params }: { params: { slug: string } }) {
  const post = BLOG_POSTS.find((p) => p.slug === params.slug);

  if (!post) {
    notFound();
  }

  const articleSchema = generateArticleSchema({
    title: post.title,
    description: post.excerpt,
    publishedAt: post.publishedAt,
    updatedAt: post.updatedAt,
    author: post.author,
    slug: post.slug,
    image: getAbsoluteImageUrl(getBlogHeroImage(post.slug, post.heroImage), getBaseUrl()),
  });

  const hub = post.hubSlug
    ? CONTENT_HUBS.find((h) => h.hubSlug === post.hubSlug)
    : undefined;
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: "/" },
    { name: "Blog", url: "/blog" },
    ...(hub ? [{ name: hub.title, url: categoryHubPath(hub.hubSlug) }] : []),
    { name: post.title, url: `/blog/${post.slug}` },
  ]);

  const faqSchema = post.faqs.length > 0 ? generateFAQSchema(post.faqs) : null;
  const speakableSchema = post.quickAnswer
    ? generateSpeakableSchema({ name: post.title, path: `/blog/${post.slug}` })
    : null;

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {faqSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
      )}
      {speakableSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(speakableSchema) }}
        />
      )}
      <BlogPostLayout post={post} formatDate={formatDate} />
    </>
  );
}
